Update release.yaml

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -67,7 +67,7 @@ jobs:
       - name: Check badges on public gateway
         run: |
           #Check IPFS Status (on gateway)
-          curl --write-out '%{http_code}' --silent --output /dev/null --fail https://ipfs.io/ipfs/${{ steps.badges.outputs.hash }}
+          curl --write-out '%{http_code}' --silent --output /dev/null --fail --retry 2 https://ipfs.io/ipfs/${{ steps.badges.outputs.hash }} || echo "Failed check"
       - name: Upload badges to IPNS
         if: ${{ always() }}
         run: |
@@ -77,7 +77,7 @@ jobs:
         if: ${{ always() }}
         run: |
           #Check IPNS Status (on gateway)
-          curl --write-out '%{http_code}' --silent --output /dev/null --fail https://ipfs.io/ipns/${{ steps.badges.outputs.key }}
+          curl --write-out '%{http_code}' --silent --output /dev/null --fail --retry 2 https://ipfs.io/ipns/${{ steps.badges.outputs.key }} || echo "Failed check"
       - name: Upload packages to IPFS
         id: ipfs
         run: |
